### ISSUE TITLE
Remove placeholder on setContent()

### ISSUE THREAD

**Issue by secu2** [mohan999/tinymce-placeholder#1]
The placeholder stays when you call the setContent() method on the editor.
Resulting in this:
![capture d ecran 2015-05-06 a 14 34 43](https://cloud.githubusercontent.com/assets/1344529/7493179/b78d70e4-f3fe-11e4-9158-911d19cf761e.png)
———
I'd suggest this fix:
```javascript
editor.on('BeforeSetContent', function(e) {
            if(e['content'] !== ""){
                label.hide();
            }else{
                label.show();
            }
        });
```

**Comment by lepinejf** [comment]
Thanks for the fix
